### ISSUE TITLE
KeyError: "None of [Index(['PosNeg_MS2filter20'], dtype='object')] are in the [index]"

### ISSUE THREAD

**Issue by theo-llewellyn** [tiagolbiotech/NPOmix_python#4]
Hello,

I'm currently running into an error related to the mgf file. I have a large mgf file from MZmine3 with 7485 ions in total from an LCMS/MS analysis of around 80 samples run in both +ve and -ve ion mode. When I run NPOmix using a single concatenated mgf file (PosNeg_MS2filter20.mgf) the programme runs without errors but the programme seems to interpret it as a single ion, i.e. there is only one row in the testing_df-NPOmix1.0-20230126.txt and final_df-NPOmix1.0-20230126.txt output files with the metabolite ID 'PosNeg_MS2filter20'. If I try to separate the mgf into individual mgfs for each ion (named PosNeg_MS2filter20_1, PosNeg_MS2filter20_2 etc) I get the following error:

Traceback (most recent call last):
  File "/rds/general/user/tbl19/home/software/NPOmix_python_2/NPOmix_python/npomix.py", line 546, in <module>
    run_time = run_main(mgf_folder,merged_ispec_mat_file,LCMS_folder,ena_df_file,input_bigscape_net,antismash_folder,results_folder)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/tbl19/home/software/NPOmix_python_2/NPOmix_python/npomix.py", line 509, in run_main
    ispec_mat = get_ispec_mat(speclist,LCMS_folder,fmgf)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/tbl19/home/software/NPOmix_python_2/NPOmix_python/npomix.py", line 183, in get_ispec_mat
    ispec_mat.loc[mtmp['specids'], filt_specn[i]] = mtmp['scores'].tolist()
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/tbl19/home/anaconda3/envs/NPOmix-env/lib/python3.11/site-packages/pandas/core/indexing.py", line 814, in __setitem__
    indexer = self._get_setitem_indexer(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/tbl19/home/anaconda3/envs/NPOmix-env/lib/python3.11/site-packages/pandas/core/indexing.py", line 697, in _get_setitem_indexer
    return self._convert_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/tbl19/home/anaconda3/envs/NPOmix-env/lib/python3.11/site-packages/pandas/core/indexing.py", line 896, in _convert_tuple
    keyidx = [self._convert_to_indexer(k, axis=i) for i, k in enumerate(key)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/tbl19/home/anaconda3/envs/NPOmix-env/lib/python3.11/site-packages/pandas/core/indexing.py", line 896, in <listcomp>
    keyidx = [self._convert_to_indexer(k, axis=i) for i, k in enumerate(key)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/tbl19/home/anaconda3/envs/NPOmix-env/lib/python3.11/site-packages/pandas/core/indexing.py", line 1396, in _convert_to_indexer
    return self._get_listlike_indexer(key, axis)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/tbl19/home/anaconda3/envs/NPOmix-env/lib/python3.11/site-packages/pandas/core/indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/tbl19/home/anaconda3/envs/NPOmix-env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6113, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/rds/general/user/tbl19/home/anaconda3/envs/NPOmix-env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6173, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['PosNeg_MS2filter20'], dtype='object')] are in the [index]"


I have attached an example of one of the separated mgf files. The BGC files and outputs all seem correct and I was able to succesfully run NPOmix using the test datasets mentioned in the walkthroughs.

Thanks,
Theo
[PosNeg_MS2filter20_1.txt](https://github.com/tiagolbiotech/NPOmix_python/files/10534394/PosNeg_MS2filter20_1.txt)

**Comment by theo-llewellyn** [comment]
I've been troubleshooting and I think my mgf files might need to be renamed with CCMSLIB id's from the gnps_names_list file. I renamed them using that file and it ran without errors. Apologies for the preemptive post
